version: 0.2

phases:

  install:
    commands:

      - echo "commented all dependencies installation "
      #- yum list
      #- apt-get update -y
      #- apt-get install -y software-properties-common
      #- add-apt-repository ppa:openjdk-r/ppa
      #- apt-get update -y
      #- apt-get install -y openjdk-8-jdk
      #- apt-get install -y maven 
  pre_build:
    commands:
      - echo Logging in to Amazon ECR is commented Mate...
      #- $(aws ecr get-login --no-include-email --region us-east-2)
  build:
    commands:
      - echo "Starting GTR--- python OCELOT build"
      - echo " << Start Date `date` >>"
      #- tar cvf python-http-project.tar *
  post_build:
    commands:
      - echo "Running Docker commands "
      #- docker build -t opstomcatdocker .
      #- docker tag opstomcatdocker 019894823873.dkr.ecr.us-east-2.amazonaws.com/opstomcatdocker:v5
      #- echo "Pushing Docker image to ECR--- Commenting Docket PUSH as ECR is not ready in LAB yet"
      #- docker push 019894823873.dkr.ecr.us-east-2.amazonaws.com/opstomcatdocker:v5
artifacts:
  files:
    - '**/*'
